concurrent = 1
check_interval = 0

[[runners]]
  executor = "docker"
  [runners.docker]
    image = "ubuntu"
    volumes = [
      "/usr/bin/docker:/usr/bin/docker"
      "/var/run/docker.sock:/var/run/docker.sock",
      "/usr/libexec/docker/:/usr/libexec/docker/"
      "/cache"
    ]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
